baner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('accounts.urls', namespace='accounts')),


]



handler404 = 'home.views.custom_404'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('s/', d, name='1'),
    path('banners/<str:name>', BannersView.as_view(), name='banners'),
    path('titles/', TitlesView.as_view(), name='Titles'),
    path('showbanners/<shenase>/', BannersDetailView.as_view(), name='showbanners'),
    path('generate/<shenase>/', GeneratePhotosView.as_view(), name='generate_photos'),
    path('createimage/', ImagesView.as_view(), name='createimage'),
    path('createimagetwomadah/', ImagesTwoMadahView.as_view(), name='createimagetwomadah'),
    path('ajax/subcategories/', get_subcategories, name='get_subcategories'),  # اضافه کردن این خط
    path('banners/<shenase>/like/', like_product, name='like_product'),
    path('buy_banner/<int:shenaseh_generated>/<str:c_or_v>', buy_banner, name='buy_banner'),
]

home/forms.py
from .models import *
from django import forms

MONASEBAT_CHOICES = [
    ('---', '---'),
    ('mohammad', 'حضرت محمد (ص)'),
    ('ali', 'امام علی بن ابی‌طالب (ع)'),
    ('fateme', 'حضرت فاطمه الزهرا (س)'),
    ('hasan', 'امام حسن (ع)'),
    ('hosein', 'امام حسین (ع)'),
    ('moharam', 'محرم'),
    ('sajad', 'امام زین‌العابدین (ع)'),
    ('baqer', 'امام محمد باقر (ع)'),
    ('sadeq', 'امام جعفر صادق (ع)'),
    ('kazem', 'امام موسی کاظم (ع)'),
    ('reza', 'امام علی رضا (ع)'),
    ('javad', 'امام جواد (ع)'),
    ('naqi', 'امام علی نقی (ع)'),
    ('asgari', 'امام حسن عسگری (ع)'),
    ('mahdi', 'حضرت مهدی (ع)'),
    ('ghadir' , 'عید غدیر'),
    ('ali_asghar' , 'حضرت علی اصغر (ع)'),
    ('abas' , 'حضرت عباس (ع)'),
    ('zeynab' , 'حضرت زینب (س)'),
    ('ghasem' , 'حضرت قاسم (ع)'),
    ('ali_akbar' , 'حضرت علی اکبر (ع)'),
    ('roghaye' , 'حضرت رقیه (س)'),
    ('masomeh' , 'حضرت معصومه (س)'),
    ('abdol_azim_hasani' , 'حضرت عبدالعظیم حسنی (ع)'),
    ('omolbanin' , 'حضرت ام البنین (س)'),


]
VELADAT_OR_SHAHADAT_CHOICES = [
    ('veladat', 'ولادت'),
    ('shahadat', 'شهادت'),
    ('digar', 'دیگر')
]








class ImagesForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True, label='Category')
    subcategory = forms.ModelChoiceField(queryset=SubCategory.objects.none(), required=True, label='Subcategory')

    class Meta:
        model = images
        fields = [
            'title', 'shenaseh', 'image_asli', 'image_kham', 'leye_baz', 'to_madah', 'Price_virtual', 'Price_chap',
            'Scale_x_y_madah', 'x_madah', 'y_madah', 'font_size_madah', 'default_hex_color_madah', 'font_name_madah',
            'Scale_x_y_sokhanran','x_sokhanran', 'y_sokhanran', 'font_size_sokhanran', 'default_hex_color_sokhanran', 'font_name_sokhanran',
            'x_address', 'y_address', 'font_size_addres', 'default_hex_color_address', 'font_name_address','Scale_x_y_address', 'x_zaman',
            'y_zaman', 'font_size_zaman', 'default_hex_color_zaman', 'font_name_zaman','Scale_x_y_zaman', 'x_esmheyat', 'y_esmheyat',
            'font_size_esmheyat', 'default_hex_color_esmheyat', 'font_name_esmheyat','Scale_x_y_esmheyat', 'two_madah_True', 'subcategory'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # حذف فیلد shenaseh از فرم
        self.fields.pop('shenaseh', None)

        # اضافه کردن کلاس‌ها به تمامی فیلدها به جز to_madah
        for field_name, field in self.fields.items():
            if field_name != 'to_madah':
                field.widget.attrs.update({'class': 'form-control col-6'})

        # افزودن کلاس خاص برای چک‌باکس
        self.fields['to_madah'].widget.attrs.update({'class': 'form-check-input'})

        # فیلتر زیر دسته‌های مرتبط با دسته بندی انتخاب شده
        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields['subcategory'].queryset = SubCategory.objects.filter(category_id=category_id).order_by('name')
            except (ValueError, TypeError):
                pass  # اگر مقدار نامعتبر باشد، هیچ زیر دسته‌ای نمایش داده نشود
        elif self.instance.pk and self.instance.category:
            self.fields['subcategory'].queryset = self.instance.category.subcategories.order_by('name')




class ImagesTwoMadahForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True, label='Category')
    subcategory = forms.ModelChoiceField(queryset=SubCategory.objects.none(), required=True, label='Subcategory')

    class Meta:
        model = imagesTowMadah
        fields = [
            'title', 'shenaseh', 'image_asli', 'image_kham', 'leye_baz', 'Price_virtual', 'Price_chap',
            'Scale_x_y_madah', 'x_madah', 'y_madah', 'font_size_madah', 'default_hex_color_madah', 'font_name_madah',
            'x_madah2', 'y_madah2', 'font_size_madah2', 'default_hex_color_madah2', 'font_name_madah2','Scale_x_y_madah2',
            'x_sokhanran', 'y_sokhanran', 'font_size_sokhanran', 'default_hex_color_sokhanran', 'font_name_sokhanran','Scale_x_y_sokhanran',
            'x_address', 'y_address', 'font_size_addres', 'default_hex_color_address', 'font_name_address','Scale_x_y_address', 'x_zaman',
            'y_zaman', 'font_size_zaman', 'default_hex_color_zaman', 'font_name_zaman','Scale_x_y_zaman', 'x_esmheyat', 'y_esmheyat',
            'font_size_esmheyat', 'default_hex_color_esmheyat', 'font_name_esmheyat','Scale_x_y_esmheyat','subcategory'
        ]


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # حذف فیلد shenaseh از فرم
        self.fields.pop('shenaseh', None)


        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control col-6'})

        # فیلتر زیر دسته‌های مرتبط با دسته بندی انتخاب شده
        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields['subcategory'].queryset = SubCategory.objects.filter(category_id=category_id).order_by('name')
            except (ValueError, TypeError):
                pass  # اگر مقدار نامعتبر باشد، هیچ زیر دسته‌ای نمایش داده نشود
        elif self.instance.pk and self.instance.category:
            self.fields['subcategory'].queryset = self.instance.category.subcategories.order_by('name')



class LikeForm(forms.ModelForm):
    class Meta:
        model = Like
        fields = ['product']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].widget = forms.HiddenInput()

home/views.py
import random
import os
import time
import threading
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.urls import reverse
from django.http import HttpResponse
from django.contrib import messages
from .forms import *
from .models import *
from django.conf import settings
from django.templatetags.static import static
from PIL import Image, ImageDraw, ImageFont
import arabic_reshaper
from bidi.algorithm import get_display
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from itertools import chain

def delete_file_after_delay(orginal_file_path, file_path, delay):
    def delete_file():
        time.sleep(delay)
        if os.path.exists(file_path):
            os.remove(file_path)
            os.remove(orginal_file_path)
            print(f'{file_path} has been deleted.')
        else:
            print(f'{file_path} does not exist.')

    threading.Thread(target=delete_file).start()





class HomeView(View):
    def get(self, request):
        latest_for_objects = monasebat_hay_bazdik.objects.order_by('-id')[:3]
        last_tuo_tarhay_akharin_monasebat = tarh_hay_akhrin_monasebat.objects.order_by('-id')[:2]
        vitrin = Vitrin_home.objects.order_by('-id')[:2]

        content = {
            'latest_for_objects': latest_for_objects,
            'last_tuo_tarhay_akharin_monasebat': last_tuo_tarhay_akharin_monasebat,
            'vitrin':vitrin
        }
        return render(request, 'home.html', content)


def mokap(foreground_image_path, final_image_path):
    background = Image.open(os.path.join(settings.BASE_DIR, 'static', 'mokap.jpg'))
    foreground = Image.open(foreground_image_path)

    if foreground.mode != 'RGBA':
        foreground = foreground.convert('RGBA')

    if foreground.width > foreground.height:
        new_width = 480
        aspect_ratio = foreground.height / foreground.width
        new_height = int(new_width * aspect_ratio)
    else:
        new_height = 480
        aspect_ratio = foreground.width / foreground.height
        new_width = int(new_height * aspect_ratio)

    foreground = foreground.resize((new_width, new_height), Image.LANCZOS)

    mask = Image.new('L', (new_width, new_height), 0)
    draw = ImageDraw.Draw(mask)
    radius = 20
    draw.rounded_rectangle([(0, 0), (new_width, new_height)], radius, fill=255)

    foreground.putalpha(mask)

    bg_width, bg_height = background.size
    fg_width, fg_height = foreground.size

    center_x = (bg_width - fg_width) // 2
    center_y = (bg_height - fg_height) // 2

    background.paste(foreground, (center_x, center_y), foreground)
    background.save(final_image_path, quality=95)




class ImagesView(View):
    form_class = ImagesForm
    template_name = 'image_form.html'
    success_url = reverse_lazy('home:home')  # به صفحه‌ای که پس از ذخیره موفقیت‌آمیز منتقل می‌شود

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            # ذخیره نکردن فرم بلافاصله و دریافت شیء مربوطه
            image_instance = form.save(commit=False)
            # تنظیم فیلد created_by به کاربر لاگین شده
            image_instance.created_by = request.user
            # ذخیره نهایی شیء
            image_instance.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form})

    def dispatch(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == 'GET':
            return self.get_subcategories(request)
        return super().dispatch(request, *args, **kwargs)



class ImagesTwoMadahView(View):
    form_class = ImagesTwoMadahForm
    template_name = 'image_form.html'
    success_url = reverse_lazy('home:home')  # به صفحه‌ای که پس از ذخیره موفقیت‌آمیز منتقل می‌شود

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form,'twoMadahForm': True})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            # ذخیره نکردن فرم بلافاصله و دریافت شیء مربوطه
            image_instance = form.save(commit=False)
            # تنظیم فیلد created_by به کاربر لاگین شده
            image_instance.created_by = request.user
            # ذخیره نهایی شیء
            image_instance.save()
            messages.success(request, 'عکس با موفقیت ذخیره شد')
            return redirect(self.success_url)

        return render(request, self.template_name, {'form': form})

    def dispatch(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == 'GET':
            return self.get_subcategories(request)
        return super().dispatch(request, *args, **kwargs)


def get_subcategories(request):
    category_id = request.GET.get('category')
    if category_id:
        category = Category.objects.get(id=category_id)
        subcategories = SubCategory.objects.filter(category_id=category_id).order_by('name')
        subcategory_list = [{'id': subcategory.id, 'name': f"{subcategory.name} {category.title}"} for subcategory in subcategories]
        return JsonResponse({'subcategories': subcategory_list})
    return JsonResponse({'subcategories': []})


class BannersDetailView(View):
    def get(self, request, shenase):
        if images.objects.filter(shenaseh=shenase).exists():
            product = get_object_or_404(images, shenaseh=shenase)


        elif imagesTowMadah.objects.filter(shenaseh=shenase).exists():
            product = get_object_or_404(imagesTowMadah, shenaseh=shenase)

        if request.user.is_authenticated:
            if images.objects.filter(shenaseh=shenase).exists():
                user_likes = Like.objects.filter(user=request.user, product=product).exists()
            elif imagesTowMadah.objects.filter(shenaseh=shenase).exists():
                user_likes = LikeTwoMadah.objects.filter(user=request.user, product=product).exists()
            return render(request, 'banner_detale.html', {'object': product, 'user_likes': user_likes})
        return render(request, 'banner_detale.html', {'object': product, 'user_likes': None})


class TitlesView(View):
    def get(self, request):
        objects = Category.objects.all()
        return render(request, 'Titles.html', {'objects': objects})


class BannersView(View):
    def get(self, request, name):
        category = Category.objects.get(name=name)

        # فیلتر کردن تمام تصاویر (محصولات) مرتبط با این معصوم
        products = images.objects.filter(subcategory__category=category)
        products_tow_madah = imagesTowMadah.objects.filter(subcategory__category=category)

        # ترکیب کردن دو QuerySet
        combined_products = list(chain(products, products_tow_madah))
        return render(request, 'banners.html', {
            'objects': combined_products,
        })


def hex_to_rgb(hex_code):
    hex_code = hex_code.lstrip('#')
    return tuple(int(hex_code[i:i + 2], 16) for i in (0, 2, 4))


def add_text_to_image(img, text, font_name, font_path, font_size, color, position, c_or_r):
    position = list(position)
    if font_name == 'Yekan':
        position[1] = position[1] - 6
    elif font_name == 'Lyon':
        position[1] = position[1] - 4
    elif font_name == 'Almas':
        font_size = font_size - 3
        position[1] = position[1] - 20
    elif font_name == 'Mj_Sayeh':
        font_size = font_size + 8
        position[1] = position[1] - 8
    elif font_name == 'yakan_bold':
        position[1] = position[1] - 37
    position = tuple(position)
    draw = ImageDraw.Draw(img)
    text_color = tuple(color)
    font = ImageFont.truetype(font_path, font_size)
    reshaped_text = arabic_reshaper.reshape(text)
    bidi_text = get_display(reshaped_text)

    bbox = draw.textbbox((0, 0), bidi_text, font=font)
    text_width = bbox[2] - bbox[0]
    text_height = bbox[3] - bbox[1]
    image_width, image_height = img.size

    if c_or_r == 'right':

        x = image_width - int(position[0]) - text_width
    elif c_or_r == 'center':

        if position[0] == 'center':
            x = (image_width - text_width) / 2
        else:
            x = int(position[0]) - (text_width / 2)
    else:
        x = int(position[0])
    y = position[1] - (text_height / 2)

    draw.text((x, y), bidi_text, font=font, fill=text_color)


class GeneratePhotosView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return super(GeneratePhotosView, self).dispatch(request, *args, **kwargs)
        else:
            messages.error(request, 'شما باید وارد شوید و یا ثبت نام کنید', 'l_r')
            return redirect('accounts:register')

    def get(self, request, shenase):

        if images.objects.filter(shenaseh=shenase).exists():
            image = get_object_or_404(images, shenaseh=shenase)

        elif imagesTowMadah.objects.filter(shenaseh=shenase).exists():
            image = get_object_or_404(imagesTowMadah, shenaseh=shenase)

        context = {
            'image': image,
            'font_size_madah': int(image.font_size_madah),
            'font_name_madah': image.font_name_madah,
            'font_name_sokhanran': image.font_name_sokhanran,
            'font_size_sokhanran': image.font_size_sokhanran,
            'font_size_addres': image.font_size_addres,
            'font_name_addres': image.font_name_address,
            'font_size_zaman': image.font_size_zaman,
            'font_name_zaman': image.font_name_zaman,
            'font_size_esmheyat': image.font_size_esmheyat,

home/templates/Titles.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% for object in objects %}

                <div class="col-xxl-3 col-xl-4 col-lg-4 col-md-6 col-12 text-center mt-3">
                    <a class="fs-1 btn btn-outline-dark w-100" href="{% url 'home:banners' object.name %}" style="font-family:'Nastaliq' ;">{{ object.title }}</a>
                </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

home/templates/banner_detale.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'w3css.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

{% block content %}
    {# like form #}
    <div class="container me-auto m-auto row">
    <form id="like-form"  method="post" action="{% url 'home:like_product' object.shenaseh %}">
        {% csrf_token %}
        <button type="button" class="w-100 btn btn-outline-light " id="like-button">
            {% if user_likes %}
                <i class="bi bi-heart-fill text-danger"></i>
            {% else %}
                <i class="bi bi-heart text-danger" ></i>
            {% endif %}
        </button>

    </form>
    <p>Likes: <span id="likes-count">{{ object.likes.count }}</span></p>
    <div class="row text-center">
    <div class="col-xl-6 col-12 text-center mb-3">
    <img src="/static/images_asli/{{ object.shenaseh }}.jpg" class="rounded-2 " style="width: 400px">
        <div class="d-grid">
    <a href="{% url 'home:generate_photos' object.shenaseh %}" class="btn btn-primary btn-block mt-3">ساخت بنر با این طرح </a><br>
        </div>
    </div>
    {% if object.to_madah %}


    <div class="col-xl-6 col-12 text-center mb-3">
    <img src="/static/images_asli/{{ object.two_madah_True.shenaseh }}.jpg" class="rounded-2" style="width: 400px">
        <div class="d-grid">
            <a href="{% url 'home:generate_photos' object.two_madah_True.shenaseh %}" class="btn btn-primary btn-block mt-3">ساخت بنر <b>دو مداحه</b> با این طرح </a><br>
        </div>    </div>
        {% endif %}
    </div>
    <script>
        $(document).ready(function() {
            $('#like-button').click(function() {
                var form = $('#like-form');
                $.ajax({
                    type: form.attr('method'),
                    url: form.attr('action'),
                    data: form.serialize(),
                    success: function(response) {
                        if (response.liked) {
                            $('#like-button').html('<i class="bi bi-heart-fill text-danger"></i>');
                        } else {
                            $('#like-button').html('<i class="bi bi-heart text-danger"></i>');
                        }
                        $('#likes-count').text(response.likes_count);
                    },
                    error: function(response) {
                        alert(response.responseJSON.error);
                    }
                });
            });
        });
    </script>
    {# end like form #}
    </div>
{% endblock %}

home/templates/banners.html
{% extends 'base.html' %}
{% load static %}
{% block head %} <link rel="stylesheet" href="{% static 'css/banners.css' %}"> {% endblock %}
{% block content %}
<div class="container mt-2">
    <!-- Carousel -->
<div id="demo" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    {% for i in objects %}
        <button type="button" data-bs-target="#demo" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></button>
    {% endfor %}
  </div>

  <!-- The sli/ deshow/carousel -->
  <div class="carousel-inner rounded-3">
      {% for object in objects %}
          <div class="carousel-item {% if forloop.first %} active {% endif %}">
              <img src="../static/images_asli/{{ object.shenaseh }}.jpg" alt="Los Angeles" class="d-block" style="width:100%">
              <div class="carousel-caption rounded-4" style="background-color: rgba(0,0,0,0.55);">
            <a href="{% url 'home:showbanners' object.shenaseh %}" class="btn btn-primary ">
                عملیات
            </a>

      </div>
    </div>

      {% endfor %}
  </div>

  <!-- Left and right controls/icons -->
  <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
    <span class="carousel-control-next-icon"></span>
  </button>
</div>
</div>
{% endblock %}

home/templates/create_mahsol_chek.html
{% extends 'base.html' %}
{% block head %}{% endblock %}
{% block content %}
    <div class="container-fluid mt-3">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
        {% if eror %}
          <div class="alert alert-danger" >
              <strong>خطا!</strong> {{ eror }}
          </div>
        {% endif %}
    </form>
    <div>
{% endblock %}

home/templates/image_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <h1>ایجاد تصویر جدید</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
                <div class="col-6 mt-3">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}

                    {% if field.errors %}
                        <div class="text-danger">
                            {% for error in field.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary mt-3 mb-5">ذخیره</button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if not twoMadahForm %}
        // Script for handling 'to_madah' checkbox
        var toMadahCheckbox = document.querySelector('input[name="to_madah"]');
        var twoMadahFieldContainer = document.querySelector('select[name="two_madah_True"]').closest('div');

        function toggleTwoMadahField() {
            if (toMadahCheckbox.checked) {
                twoMadahFieldContainer.style.display = 'block';
            } else {
                twoMadahFieldContainer.style.display = 'none';
            }
        }

        // Initial check
        toggleTwoMadahField();

        // Add event listener for checkbox
        toMadahCheckbox.addEventListener('change', toggleTwoMadahField);
        {% endif %}
        // Script for handling category and subcategory
        var categoryField = document.querySelector('select[name="category"]');
        var subcategoryField = document.querySelector('select[name="subcategory"]');

        categoryField.addEventListener('change', function() {
            var categoryId = this.value;
            var url = "{% url 'home:get_subcategories' %}?category=" + categoryId;

            fetch(url)
                .then(response => response.json())
                .then(data => {
                    subcategoryField.innerHTML = '';  // Clear current subcategories
                    data.subcategories.forEach(function(subcategory) {
                        var option = document.createElement('option');
                        option.value = subcategory.id;
                        option.textContent = subcategory.name; // Combined name
                        subcategoryField.appendChild(option);
                    });
                });
        });
    });
</script>
{% endblock %}

home/templates/list_mahsol_chek.html
<!DOCTYPE html>
<html>
<head>
    <title>لیست محصولات چک</title>
</head>
<body>
    <h1>لیست محصولات چک</h1>
    <ul>
        {% for item in items %}
            <li>
                <p>نوع فایل: {{ item.file_type }}</p>
                <p>مناسبت محصول: {{ item.monasebat_mahsol }}</p>
                <p>ولادت یا شهادت: {{ item.veladat_or_shahadat }}</p>
                <p>تصویر پیش‌نمایش:</p>
                <img src="{{ item.image_preview.url }}" alt="تصویر پیش‌نمایش" width="100">
                <p>لایه باز:</p>
                <a href="{{ item.laye_baz.url }}">دانلود فایل لایه باز</a>
                <br>
                <a href="../approve_mahsol_chek/{{ item.pk }} ">تأیید</a>
            </li>
            <hr>
        {% endfor %}
    </ul>
</body>
</html>

home/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

home/templates/view_img.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <style>
        body{
            background-color: #eeeeee !important;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-xxl-6 col-lg-6 col-xl-6 col-md-12 col-sm-12 col-12 text-center mt-4">
                <img src="{% static image_name %}" style="width: 90% ;" class="rounded-3">
            </div>
            <div class="col-xxl-6 col-lg-6 col-xl-6 col-md-12 col-sm-12 col-12  mt-4">
                  <div class="d-grid gap-3">
                    {% for i in image %}
                    <a type="button" href="{% url 'home:buy_banner' i.shenaseh 'c' %}" class="btn btn-primary btn-block">دریافت فایل با کیفیت و مناسب چاپ<span class="badge rounded-pill bg-info bg-opacity-50">70,000 تومان</span></a>
                    <button type="button" class="btn btn-primary btn-block">دریافت فایل مناسب وب (مناسب انتشار مجازی)   <span class="badge rounded-pill bg-info bg-opacity-50">70,000 تومان</span></button>
                    <a type="button" href="{% url 'home:generate_photos' i.shenaseh %}" class="btn btn-primary btn-block">برگشت به صفحه طراحی<span class="badge rounded-pill bg-info bg-opacity-50">70,000 تومان</span></a>
                    {% endfor %}
                  </div>
                <div>
                    <br>
                    <div class="card">
                      <div class="card-body">
                    به نکات زیل توجه فرماید

                          <div class="row mt-3">
                              <div class="col-2">
                          <script class="d-inline-block" src="https://www.zarinpal.com/webservice/TrustCode" type="text/javascript"></script>
                          </div>
                              <div class="col-10">
                              <h6 class=" mt-1 d-inline-block"><i class="bi bi-caret-left-fill"></i> پرداخت از طریق درگاه پرداخت زرین پال انجام میشود</h6>
                      <h6 class=" mt-1 d-inline-block"><i class="bi bi-caret-left-fill"></i> پس از پرداخت مبلغ نسبت به دانلود فایل اقدام کنید<br><br>( پس از خروج از صفحه فایل دیگر در دسترس شما نخاهد بود )</h6></div>
                              </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/viwe_img_asli.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container text-center mt-3">
<div class="row text-center">
<div class="col-6 me-auto ms-auto">
    <img src="{% static banner %}" width="400px" class="rounded-4">
    <a download href="{% static banner %}" class="btn w-100 btn-outline-primary mt-3"> دانلود عکس </a>
</div>

</div>
</div>
{% endblock %}