accounts/urls.py
# urls.py
from django.urls import path, include
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/', VerifyCodeView.as_view(), name='verify_code'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('verify_payment/', VerifyPaymentView.as_view(), name='verify_payment'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),
    path('Reset_password/', ForgotPasswordView.as_view(), name='Reset_password'),
    path('verify_reset_pass/', VerifyCodeResetPassView.as_view(), name='verify_code_reset_pass'),
    path('resend_verification_code/', ResendVerificationCodeView.as_view(), name='resend_verification_code'),

]

baner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('accounts.urls', namespace='accounts')),


]



handler404 = 'home.views.custom_404'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('s/', d, name='1'),
    path('banners/<str:name>', BannersView.as_view(), name='banners'),
    path('titles/', TitlesView.as_view(), name='Titles'),
    path('showbanners/<shenase>/', BannersDetailView.as_view(), name='showbanners'),
    path('generate/<shenase>/', GeneratePhotosView.as_view(), name='generate_photos'),
    path('createimage/', ImagesView.as_view(), name='createimage'),
    path('createimagetwomadah/', ImagesTwoMadahView.as_view(), name='createimagetwomadah'),
    path('ajax/subcategories/', get_subcategories, name='get_subcategories'),  # اضافه کردن این خط
    path('banners/<shenase>/like/', like_product, name='like_product'),
    path('buy_banner/<int:shenaseh_generated>/<str:c_or_v>', buy_banner, name='buy_banner'),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
import random, os, string

def random_string(length=10):
    """Generate a random string of fixed length."""
    letters = string.ascii_letters
    return ''.join(random.choice(letters) for i in range(length))

def rename_random_file(instance, filename):
    """Rename file to a random string."""
    ext = filename.split('.')[-1]
    new_filename = f"{random_string()}.{ext}"
    return os.path.join('profile_images/', new_filename)

class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        """Create and return a regular user."""
        if not username:
            raise ValueError(_('The Username field must be set'))

        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        """Create and return a superuser with superuser permissions."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(username, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=15, unique=True)
    username = models.CharField(max_length=30, unique=True)
    # Remove password field as it is handled by AbstractBaseUser
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    profile_picture = models.ImageField(upload_to=rename_random_file, null=True, blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['phone_number', 'first_name', 'last_name']
    
    def __str__(self):
        return self.username

accounts/views.py
from allauth.account.signals import password_reset
from django.shortcuts import render, redirect, HttpResponse
from django.template.context_processors import media
from django.utils.text import phone2numeric
from django.views import View
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from kavenegar import KavenegarAPI, APIException, HTTPException
from .forms import UserRegistrationForm, VerificationCodeForm, UserLoginForm, CustomUserForm, ForgotPasswordForm,VerificationCodeResetPassForm
from .models import CustomUser
from home.models import imagesTowMadah
from django.contrib.auth.mixins import LoginRequiredMixin
from zeep import Client
import random
from datetime import timedelta , datetime
from django.utils import timezone
import pytz

class RegisterView(View):
    template_name = 'accounts/register.html'
    form_class = UserRegistrationForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.success(request, 'شما قبلا وارد شده‌اید', 'primary')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd.get('username')
            phone_number = cd.get('phone_number')
            password = cd.get('password')
            first_name = cd.get('first_name')
            print(first_name)
            last_name = cd.get('last_name')

            # Generate random verification code
            verification_code = random.randint(10000, 100000)

            try:
                api = KavenegarAPI('7137636B3533527375376E4266717465386F712F426153787443696D6E363859714F657A4B3754336434513D')
                params = {
                    'receptor': phone_number,
                    'template': 'register',
                    'token': verification_code,
                    'type': 'sms',
                }
                response = api.verify_lookup(params)
            except (APIException, HTTPException) as e:
                messages.error(request, 'خطایی در ارسال پیامک رخ داده است. لطفاً دوباره تلاش کنید.')
                return render(request, self.template_name, {'form': form})

            # Store verification code and user info in session
            request.session['verification_code'] = verification_code
            request.session['verification_code_sent_time'] = timezone.now().timestamp()
            request.session['username'] = username
            request.session['phone_number'] = phone_number
            request.session['password'] = password
            request.session['first_name'] = first_name
            print(first_name + '1')
            request.session['last_name'] = last_name

            messages.success(request, 'یک کد تایید به شماره شما ارسال شد. لطفاً کد را وارد کنید.', 'success')
            return redirect('accounts:verify_code')
        else:
            messages.error(request, 'فرم ارسال شده معتبر نیست. لطفاً دوباره تلاش کنید.')
            return render(request, self.template_name, {'form': form})

class VerifyCodeView(View):
    template_name = 'accounts/verify_code.html'
    form_class = VerificationCodeForm

    def get(self, request):
        if request.session.get('verification_code'):
            form = self.form_class()
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('home:home')

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            entered_code = form.cleaned_data.get('code')
            print(entered_code)
            session_code = request.session.get('verification_code')
            sent_time = request.session.get('verification_code_sent_time')
            # تبدیل timestamp به datetime بدون ناحیه زمانی
            sent_time_naive = datetime.fromtimestamp(sent_time)

            # تبدیل datetime به timezone-aware با استفاده از pytz
            sent_time_aware = pytz.utc.localize(sent_time_naive)

            # اطمینان از اینکه timezone.now() نیز timezone-aware است
            now_aware = timezone.now()

            # مقایسه
            if sent_time_aware and now_aware > sent_time_aware + timedelta(minutes=1):
                messages.error(request, 'کد تایید منقضی شده است. لطفاً دوباره درخواست ارسال کد کنید.')
                return redirect('accounts:resend_verification_code')

            if int(entered_code) == int(session_code):
                username = request.session.get('username')
                password = request.session.get('password')
                first_name = request.session.get('first_name')
                last_name = request.session.get('last_name')
                phone_number = request.session.get('phone_number')

                # Create the user
                user = CustomUser.objects.create_user(
                    username=username,
                    password=password,
                    first_name=first_name,
                    last_name=last_name,
                    phone_number=phone_number
                )

                login(request, user)
                messages.success(request, 'ثبت نام با موفقیت انجام شد.', 'success')
                request.session.flush()
                return redirect('home:home')
            else:
                messages.error(request, 'کد تایید نادرست است.')
        return render(request, self.template_name, {'form': form})

class ResendVerificationCodeView(View):
    def get(self, request):
        phone_number = request.session.get('phone_number')
        if not phone_number:
            messages.error(request, 'شماره موبایل یافت نشد. لطفاً دوباره تلاش کنید.')
            return redirect('accounts:register')

        # تولید و ارسال کد تایید جدید
        verification_code = random.randint(10000, 100000)
        try:
            api = KavenegarAPI('7137636B3533527375376E4266717465386F712F426153787443696D6E363859714F657A4B3754336434513D')
            params = {
                'receptor': phone_number,
                'template': 'resendcode',
                'token': verification_code,
                'type': 'sms',
            }

            response = api.verify_lookup(params)
            request.session['verification_code'] = verification_code
            request.session['verification_code_sent_time'] = timezone.now().timestamp()
            messages.success(request, 'کد جدید به شماره شما ارسال شد.')
            return redirect('accounts:verify_code')
        except (APIException, HTTPException):
            messages.error(request, 'خطایی در ارسال پیامک رخ داده است. لطفاً دوباره تلاش کنید.')
            return redirect('../')


class LoginView(View):
    template_name = 'accounts/login.html'
    form_class = UserLoginForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.success(request, 'شما قبلا وارد شده‌اید', 'primary')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'شما وارد شدید', 'success')
                return redirect('home:home')
            messages.error(request, 'نام کاربری و یا رمز عبور نادرست است', 'warning')
        return render(request, self.template_name, {'form': form})

class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'شما با موفقیت خارج شدید', 'warning')
        return redirect('home:home')

class ForgotPasswordView(View):
    template_name = 'accounts/reset_pass.html'
    form_class = ForgotPasswordForm
    def get(self , request):
        form = self.form_class()
        return render(request , self.template_name,{'form' : form })
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data.get('phone_number')
            if not CustomUser.objects.filter(phone_number=phone_number).exists():
                messages.error(request, 'این شماره تلفن یافت نشد','danger')
                return render(request, self.template_name, {'form': self.form_class})
            request.session['verification_code_reset_pass_sent_time'] = timezone.now().timestamp()
            request.session['phone_number_for_reset_pass'] = phone_number
            verification_code = random.randint(10000, 100000)

            try:
                api = KavenegarAPI('7137636B3533527375376E4266717465386F712F426153787443696D6E363859714F657A4B3754336434513D')
                params = {
                    'receptor': phone_number,
                    'template': 'Forgot-password',
                    'token': verification_code,
                    'type': 'sms',
                }
                response = api.verify_lookup(params)
            except (APIException, HTTPException) as e:
                messages.error(request, 'خطایی در ارسال پیامک رخ داده است. لطفاً دوباره تلاش کنید.')

                return render(request, self.template_name, {'form': form})
            request.session['verification_code_for_reset_pass'] = verification_code
            messages.success(request,'کدی به شماره موبایل شما ارسال شد . آن را وارد کنید', 'success')
            return redirect('accounts:verify_code_reset_pass')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link href="{% static 'css/register.css' %}">
{% endblock %}
{% block content %}
    <div class="container-fluid ">
    <h1>ورود</h1>
    <form action="" method="post">
        {% csrf_token %}
                <!-- نمایش فیلدهای فرم بدون نمایش خطاها -->

            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="mb-1">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}


        <!-- نمایش ارورهای فرم در انتهای فرم -->
        {% if form.errors %}
            <div class="container-fluid pe-2 ps-2">
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            {{ error | safe }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}
    <input type="submit" value="ورود" style="width:250px" class="btn btn-primary">
        <a href="{% url 'accounts:Reset_password' %}" class="btn btn-outline-primary" style="text-decoration:none; width:250px">رمز عبور خود را فراموش کرده اید؟</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<style>
    .profile_img {
        width: 150px; /* عرض ثابت برای مربع */
        height: 150px; /* ارتفاع ثابت برای مربع */
        object-fit: cover; /* برش مناسب تصویر */
        border-radius: 0; /* حذف گردی */
        margin:auto;
        margin-top:10px;
    }
</style>
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 text-center">
            <!-- بخش تصویر پروفایل -->
            <div class="card mb-4">
                 <img src="/media/{{ user.profile_picture }}" class="card-img-top profile_img" style="border-radius : 100%" alt="Profile Picture">
                <div class="card-body">
                    <h4 class="card-title">{{ user.first_name }} {{ user.last_name }}</h4>
                    <p class="card-text">{{ user.username }}</p>
                    <p class="card-text">{{ user.phone_number }}</p>
                    <a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary">ویرایش پروفایل</a>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <!-- سایر اطلاعات پروفایل -->
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">اطلاعات پروفایل</h5>
                    <dl class="row">
                        <dt class="col-sm-3">نام:</dt>
                        <dd class="col-sm-9">{{ user.first_name }}</dd>
                        <dt class="col-sm-3">نام خانوادگی:</dt>
                        <dd class="col-sm-9">{{ user.last_name }}</dd>
                        <dt class="col-sm-3">نام کاربری:</dt>
                        <dd class="col-sm-9">{{ user.username }}</dd>
                        <dt class="col-sm-3">شماره موبایل:</dt>
                        <dd class="col-sm-9">{{ user.phone_number }}</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        {% if not object %}
        {% else %}
    <h1 class="mb-5">اثر های شما</h1>
                 {% for object in objects %}
                     <div class="col-3">
              <img src="../../static/images_asli/{{ object.shenaseh }}.jpg" alt="" class="rounded-3         border-2 border border-secondary" width="100%">
                     </div>
                {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link href="{% static 'css/register.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
        <script>
        function convertPersianToEnglish(input) {
            const persianNumbers = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
            const englishNumbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
            let output = input;

            for (let i = 0; i < persianNumbers.length; i++) {
                const regex = new RegExp(persianNumbers[i], 'g');
                output = output.replace(regex, englishNumbers[i]);
            }

            return output;
        }

        function handleInputChange(event) {
            event.target.value = convertPersianToEnglish(event.target.value);
        }
    </script>
<div class="container-fluid">
    <h1>ثبت نام</h1>
    <form method="post">
        {% csrf_token %}

        <!-- نمایش فیلدهای فرم بدون نمایش خطاها -->
        <div class="row">
            {% for field in form %}
                <div class="mb-3{% if field.label == 'نام' %} col-6{% elif field.label == 'نام خانوادگی' %} col-6{% elif field.label == 'ایجاد رمز عبور' %} col-6{% elif field.label == 'تکرار رمز عبور' %} col-6{% endif %}">
                    <label for="{{ field.id_for_label }}" class="mb-1">{{ field.label }}</label>
                    {% if field.label == 'شماره تلفن' %}
                          <div class="input-group " dir="ltr">
                            <span class="input-group-text">+98</span>
                        {{ field }}
                          </div>
                    {% else %}
                    {{ field }}
                    {% endif %}
                    {% if field.errors %}
                        <div class="mt-2 text-danger">
                            <i class="bi bi-exclamation-circle d-inline-block"></i>
                            <span class="error-text">{{ field.errors|safe }}</span>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        <!-- نمایش ارورهای فرم در انتهای فرم -->
        {% if form.non_field_errors %}
            <div class="container-fluid pe-2 ps-2">
                {% for error in form.non_field_errors %}
                    <div class="mt-2 text-danger">
                        <i class="bi bi-exclamation-circle d-inline-block"></i>
                        <span class="error-text">{{ error|safe }}</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <button type="submit" class="btn btn-primary">ثبت نام</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_pass.html
ror(request, 'پرداخت ناموفق بود. لطفاً دوباره تلاش کنید.', 'error')
            return redirect('home:banner_list')


تمپلیت ها :
reset_pass.html

{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 text-center ">
        <form method="post" action="">
            {% csrf_token %}
{% for field in form %}
                <div>
                    <label for="{{ field.id_for_label }}" class="mb-3 d-inline-block ">{{ field.label }}</label>
                        <div class="col-xxl-5 col-xl-6 col-lg-7 col-sm-9 col-10 m-auto">
                          <div class="input-group " style="" dir="ltr">


                            <span class="input-group-text">+98</span>
                        {{ field }}
                              <input  class="btn btn-outline-primary" type="submit" id="button-addon2" value="تایید">

                          </div>

                    {% if field.errors %}
                        <div class="mt-2 text-danger">
                            <i class="bi bi-exclamation-circle d-inline-block"></i>
                            <span class="error-text">{{ field.errors|safe }}</span>
                        </div>
                    {% endif %}
                            </div>
                </div>
            {% endfor %}
                    {% if form.non_field_errors %}
            <div class="container-fluid pe-2 ps-2">
                {% for error in form.non_field_errors %}
                    <div class="mt-2 text-danger">
                        <i class="bi bi-exclamation-circle d-inline-block"></i>
                        <span class="error-text">{{ error|safe }}</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
            </form>
    </div>

{% endblock %}

accounts/templates/accounts/verify_code.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <h1>ثبت نام</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if form.non_field_errors %}
            <div class="container-fluid pe-2 ps-2">
                {% for error in form.non_field_errors %}
                    <div class="mt-2 text-danger">
                        <i class="bi bi-exclamation-circle d-inline-block"></i>
                        <span class="error-text">{{ error|safe }}</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-6">
                <input type="submit" value="ثبت نام" class="btn btn-primary w-100">
            </div>
            <div class="col-6" style="position: relative;">
                <div id="timer-container" class="w-100" style="position: absolute; top: 0; left: 0; width: 100%; height: 43px; border-radius: 1px; display: flex; align-items: center; justify-content: center;">
                    <span id="timer-text" style="font-size: 20px; font-weight: bold; z-index: 10;">60</span>
                    <svg id="progress-border" width="100%" height="100%" viewBox="0 0 104 24" style="position: absolute; top: 0; left: 0; z-index: 5;">
                        <rect x="2" y="2" width="100%" height="20" rx="5" ry="5" fill="none" stroke="#007bff" stroke-width="1" stroke-dasharray="240" stroke-dashoffset="240" style="transition: stroke-dashoffset 1s linear;"></rect>
                    </svg>
                </div>
                <button id="resend-button" style="display: none; width: 100%;" class="btn btn-outline-primary" onclick="window.location.href='{% url 'accounts:resend_verification_code' %}'">ارسال مجدد کد</button>
            </div>
        </div>
    </form>
</div>

<script>
    // Timer functionality
    let timeLeft = 60;
    const timerText = document.getElementById('timer-text');
    const resendButton = document.getElementById('resend-button');
    const progressBorder = document.querySelector('#progress-border rect');
    const timercontainer = document.getElementById('timer-container');

    // Set the total length of the border
    const totalLength = 240; // Perimeter of the rectangle
    progressBorder.style.strokeDasharray = totalLength;
    progressBorder.style.strokeDashoffset = totalLength; // Initially empty

    const countdown = setInterval(() => {
        if (timeLeft <= 0) {
            clearInterval(countdown);
            timerText.style.display = 'none'; // Hide the timer text
            timercontainer.style.display = 'none'; // Hide the timer container

            resendButton.style.display = 'inline-block'; // Show the resend button
            resendButton.style.opacity = '1'; // Fade in the button
        } else {
            timerText.textContent = timeLeft; // Update the timer text
            // Gradually decrease stroke-dashoffset to fill the border
            const offset = totalLength * (timeLeft / 60); // Increase stroke-dashoffset gradually
            progressBorder.style.strokeDashoffset = totalLength - offset;
            timeLeft -= 1;
        }
    }, 1000);
</script>

{% endblock %}