accounts/urls.py
# urls.py
from django.urls import path, include
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/', VerifyCodeView.as_view(), name='verify_code'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('verify_payment/', VerifyPaymentView.as_view(), name='verify_payment'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),
    path('Reset_password/', ForgotPasswordView.as_view(), name='Reset_password'),
    path('verify_reset_pass/', VerifyCodeResetPassView.as_view(), name='verify_code_reset_pass'),
    path('resend_verification_code/', ResendVerificationCodeView.as_view(), name='resend_verification_code'),

]

baner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('accounts.urls', namespace='accounts')),


]



handler404 = 'home.views.custom_404'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('s/', d, name='1'),
    path('banners/<str:name>', BannersView.as_view(), name='banners'),
    path('titles/', TitlesView.as_view(), name='Titles'),
    path('showbanners/<shenase>/', BannersDetailView.as_view(), name='showbanners'),
    path('generate/<shenase>/', GeneratePhotosView.as_view(), name='generate_photos'),
    path('createimage/', ImagesView.as_view(), name='createimage'),
    path('createimagetwomadah/', ImagesTwoMadahView.as_view(), name='createimagetwomadah'),
    path('ajax/subcategories/', get_subcategories, name='get_subcategories'),  # اضافه کردن این خط
    path('banners/<shenase>/like/', like_product, name='like_product'),
    path('buy_banner/<int:shenaseh_generated>/<str:c_or_v>', buy_banner, name='buy_banner'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://mohammadjafarlo.github.io/GhadirGraphStatics/bootstrap-5.3.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://mohammadjafarlo.github.io/GhadirGraphStatics/css/navbar.css">
    <link rel="icon" href="{% static 'icon_top.png' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons-1.11.3/bootstrap-icons-1.11.3/font/bootstrap-icons.min.css' %}">

    <script src="https://mohammadjafarlo.github.io/GhadirGraphStatics/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js"></script>
        <script>
        window.onload = function() {
            // بررسی می‌کند که آیا رفرش قبلاً انجام شده است یا خیر
            if (!sessionStorage.getItem('refreshed')) {
                sessionStorage.setItem('refreshed', 'true'); // ذخیره وضعیت رفرش
                location.reload(); // رفرش صفحه
            }
        };
    </script>
    {% block head %}
    {% endblock %}
    <style>

        @font-face {
         font-family: Vazir;
         font-style: normal;
         font-weight: normal;
         src: url({% static 'fonts/Vazir.eot' %});
         src: url({% static 'fonts/Vazir.eot?#iefix' %}) format('embedded-opentype'),
         url({% static 'fonts/Vazir.woff2' %}) format('woff2'),
         url({% static 'fonts/Vazir.woff' %}) format('woff'),
         url({% static 'fonts/Vazir.ttf' %}) format('truetype');
        }
        @font-face {
         font-family: Vazir;
         font-style: normal;
         font-weight: bold;
         src: url({% static 'fonts/Vazir-Bold.eot' %});
         src: url({% static 'fonts/Vazir-Bold.eot?#iefix' %}) format('embedded-opentype'),
         url({% static 'fonts/Vazir-Bold.woff2' %}) format('woff2'),
         url({% static 'fonts/Vazir-Bold.woff' %}) format('woff'),
         url({% static 'fonts/Vazir-Bold.ttf' %}) format('truetype');
        }
         
         
        body{
        font-family: 'Vazir', Arial, sans-serif;
        font-weight:normal;
        }
        @font-face {
            font-family: Nastaliq;
            font-style: normal;
            font-weight:bold;
            src: url({% static 'font/Iran.Nastaliq.1.0.ttf' %}) format('truetype');
        }

    </style>
</head>
<body dir="rtl">

<nav class="navbar navbar-expand-xl bg-light navbar-dark sticky-top header w-100 ">
    <div class="container-fluid">
        <a href="{% url 'home:home' %}"><img src="{% static 'wm_Nastaliq (6).png' %}" width="40px" class="pb-2 ms-3"></a>
        <a class="nav-link btn-nav fs-6 btn btn-outline-secondary p-2" href="{% url 'home:Titles' %}">بنر ساز غدیر گراف&nbsp;<span style="font-size: 10px; font-weight: normal" class="badge rounded-pill bg-danger">جدید</span></a>

        <button class="navbar-toggler bg-dark-subtle" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav padding-right">
                <li class="nav-item">
                    <a class="nav-link btn-nav fs-6 btn btn-outline-secondary disabled text-dark" href="#">تایپو گرافی &nbsp;<span style="font-size: 10px; font-weight: normal" class="badge rounded-pill bg-warning">به زودی</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-nav fs-6 btn btn-outline-secondary disabled text-dark" href="#">بنر پشت منبر &nbsp;<span style="font-size: 10px; font-weight: normal" class="badge rounded-pill bg-warning">به زودی</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-nav fs-6 btn btn-outline-secondary text-dark" href="#">تماس با ما </a>
                </li>
                <hr class="m-auto">
            </ul>
            <ul class="navbar-nav navbar-nav1 me-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item m-auto">
                    <a class="nav-link btn-nav fs-6 btn btn-outline-danger p-2" href="{% url 'accounts:logout' %}">خروج از حساب</a>
                </li>
                <li class="nav-item m-auto">
                    <a class="nav-link btn-nav fs-6 btn btn-outline-primary p-2" href="{% url 'accounts:profile' %}">پروفایل شما</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link btn-nav m-auto fs-6 btn btn-outline-primary" href="{% url 'accounts:login'%}"> ورود </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-nav fs-6 btn btn-outline-primary" href="{% url 'accounts:register' %}"> ثبت نام </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>



{% if messages %}
    {% for msg in messages %}

{% if 'l_r' in msg.tags.strip %}

            <!-- The Modal -->
            <div class="modal fade" dir="rtl" id="myModal">
              <div class="modal-dialog">
                <div class="modal-content">

                  <!-- Modal Header -->
                  <div class="modal-header">
                      <button type="button" class="btn-close ms-1" data-bs-dismiss="modal"></button>
                    <h5 class="modal-title">{{ msg }}</h5>

                  </div>

                  <!-- Modal footer -->
                  <div class="modal-footer">
                    <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary" >ورود</a>
                    <a href="{% url 'accounts:register' %}" class="btn btn-outline-primary">ثبت نام</a>
                  </div>

                </div>
              </div>
            </div>

        {% else %}
        <div class="container-fluid p-2 mt-3">
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
        </div>
        {% endif %}
{% endfor %}
{% endif %}
<div class="p-1">
{% block content %}
{% endblock %}
</div>
        <button id="modal" style="display: none" data-bs-toggle="modal" data-bs-target="#myModal"></button>
    <script>
        window.onload = function() {
            document.getElementById("modal").click();
        };
    </script>
</body>
</html>